#!/usr/bin/env bash
#Tell the story of passwd
exec 3< /etc/passwd
IFS=":"
while  IFS=: read -r username _ userId groupId _ homeDirectory shell
do
	echo "The user $username is part of the $groupId gang, lives in $homeDirectory and rides $shell."
	echo "USER ID's place is protected by the passcode PASSWORD, more info about the user here: USER ID INFO"
	echo "--------------------------------------"
done <&3
exec 3<&-
