#!/usr/bin/env bash
#Now that you’ve parsed the Apache log file, let’s sort the data so you can get a better idea of what is going on.
awk '{print $1,$9}' apache-access.log | sort -V | uniq -c | sort -n | perl -e 'print reverse <>'
