#!/usr/bin/env bash
#a Bash script that displays Best School 10 times using while loop.
word="Best School"  # Replace "Hello" with the word you want to print
count=1

while [ $count -le 10 ]
do
  echo "$word"
  count=$((count + 1))
done
