#!/usr/bin/env bash
# a bash script to print "Best School" ten times and "Hi" after.
x="Best School"
y=1
while true; do
    if [ "$y" -le 10 ]; then
        echo "$x"
        y=$((y + 1))
    else
        break
    fi
done

echo "Hi"
echo "$x"
