#!/usr/bin/env bash
#a Bash script that loops from 1 to 10
i=1
word="Best School"
while [ $i -le 10 ]
do
if (($i == 4))
then
echo "bad luck"
elif (($i == 8))
then
echo "good luck"
else
echo "$word"
fi
((i++))
done
