#!/usr/bin/env bash
# Manage my process

start() {
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "Script started manage_my_process process"
}

stop() {
    if [ -f /var/run/my_process.pid ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm -rf /var/run/my_process.pid
        echo "Script deleted /var/run/my_process.pid file and stopped manage_my_process process"
    else
        echo "No running process found."
    fi
}

restart() {
    stop
    start
}

case "$1" in
    start) start ;;
    stop) stop ;;
    restart) restart ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
